spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.134.156:3306/gulimall_pms?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tPKyRnZR4PoVqdrAwUD
      secret-key: rPRbkAMAmDfULqOIYRcU5RkMWI2LIy
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
  redis:
    host: 192.168.134.156
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 6000000
      # key-prefix: CACHE_
      use-key-prefix: true
      cache-null-values: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  session:
    store-type: redis


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
#      logic-delete-value: 1
#      logic-not-delete-value: 0

server:
  port: 10000

logging:
  level:
    com.ygnn.gulimall: debug

gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
