spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tPKyRnZR4PoVqdrAwUD
      secret-key: rPRbkAMAmDfULqOIYRcU5RkMWI2LIy
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: gulimall-1008
      sms:
        host: https://fesms.market.alicloudapi.com
        path: /sms/
        skin: 1
        sign: 11
        appcode: 1aa303d2448e4a2cba38c17deb3c7e2e
  application:
    name: gulimall-third-party

server:
  port: 40000